version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault-mcp:
    build: .
    container_name: vault-mcp
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: myroot
    depends_on:
      vault:
        condition: service_healthy
    stdin_open: true
    tty: true
